# Conda environment specification. Details about the Conda environment file format:
# https://conda.io/docs/user-guide/tasks/manage-environments.html#create-env-file-manually

name: training_env
dependencies:
  - python=3.6.2
  - numpy
  - pip=21.1.1
  - scikit-learn==0.24
  - scipy
  - pip:
      - azureml-defaults
      - 'inference-schema[numpy-support]'
      - joblib
      - numpy
      - scikit-learn==0.19.1
      - scipy
channels:
  - conda-forge
