# Actions train a model on Azure Machine Learning
name: aml-train-deploy-workflow

on:
  push:
    branches:
      - master
    # paths:
    #   - 'code/*'

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    
    # Login
    - name: Az login
      run: |
         az login --service-principal --username 93964124-e148-47d5-983d-226f7304406f --password iplyGuuZJHcL0J~_X33neRHs1r1..ETkQX --tenant 72f988bf-86f1-41af-91ab-2d7cd011db47
    
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check Out Repository
      id: checkout_repository
      uses: actions/checkout@v2
    
    # Connect or Create the Azure Machine Learning Workspace
    - name: Connect/Create Azure Machine Learning Workspace
      id: aml_workspace
      uses: Azure/aml-workspace@v1
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Connect or Create a Compute Target in Azure Machine Learning
    - name: Connect/Create Azure Machine Learning Compute Target
      id: aml_compute_training
      uses: Azure/aml-compute@v1
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Submit a training run to the Azure Machine Learning
    - name: Submit training run
      id: aml_run
      uses: Azure/aml-run@v1
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

    # Register model in Azure Machine Learning model registry
    - name: Register model
      id: aml_registermodel
      uses: Azure/aml-registermodel@v1
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          run_id:  ${{ steps.aml_run.outputs.run_id }}
          experiment_name: ${{ steps.aml_run.outputs.experiment_name }}

    # Deploy model in Azure Machine Learning to ACI
    #- name: Deploy model
    #  id: aml_deploy
    #  uses: Azure/aml-deploy@v1
    #  with:
    #      azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
    #      model_name:  ${{ steps.aml_registermodel.outputs.model_name }}
    #      model_version: ${{ steps.aml_registermodel.outputs.model_version }}

    # Cliv2 
    - name: Az Install
      run: |
         az extension list
         az extension add -n ml
         echo ${{ steps.aml_registermodel.outputs.model_name }}
         echo ${{ steps.aml_registermodel.outputs.model_version }}
    
    # Deploy
    - name: Az deploy
      run: |
         az ml online-endpoint create  --resource-group amlarc-staging-test --workspace-name amlarc-staging-ws --subscription 4aaa645c-5ae2-4ae9-a17a-84b9023bc56a --file code/deploy/endpoint.yaml
         #az ml online-deployment create --resource-group amlarc-staging-test --workspace-name amlarc-staging-ws --subscription 4aaa645c-5ae2-4ae9-a17a-84b9023bc56a -n blue --file code/deploy/deployment.yaml
    
